# This kustomization is expected to be valid on long-lived refs.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ./kustomize

patchesStrategicMerge:
  # Useful for refs that change frequently, like master
  - kustomize/imagePullPolicyAlways.yaml
