FROM alpine:latest

ARG KUBECTL_VERSION=v1.17.0

#Install kubectl
ADD https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl /usr/local/bin/kubectl

ENV HOME=/config

RUN apk --no-cache add --update curl ca-certificates && \
    chmod +x /usr/local/bin/kubectl && \
    adduser kubectl -D -h /config 

USER kubectl

ENTRYPOINT ["/usr/local/bin/kubectl"]
